[google_cloud]
project = "project-id" # The project ID can be found in the GCP console https://console.cloud.google.com/
trained_models_bucket = "trained-models-bucket-name" # The bucket name where the output data will be stored.
source_images_bucket = "source-images-bucket-name" # The bucket name containing the input images for training.
source_images_directory = "source-images-directory" # The directory containing the input images for training, inside the source images bucket.
use_service_account = false
service_account = "service-account-to-use"

[vertex_ai_machine_config]
machine_type = "n1-standard-4" # The type of machine to use. Refer to: https://cloud.google.com/vertex-ai/docs/training/configure-compute#machine-types
accelerator_type = "NVIDIA_TESLA_T4" # The type of accelerator to use. Refer to: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/MachineSpec#acceleratortype
accelerator_count = 1 # Number of accelerators

[label_studio]
project_id = 1 # The ID of the Label Studio project, can be found in the URL of the project page.
url = "https://label-studio.k8s.eryx.co/" # The URL of the Label Studio instance (with an ending /).
token = "token" # The token to authenticate with the Label Studio API, refer to: https://api.labelstud.io/api-reference/introduction/getting-started#authentication

[training]
use_kfold = true
number_of_folds = 2
epochs = 1
model = "yolov8n.pt"
obb = false # Set to true when training an oriented bounding box model, see README for more details.
image_size = "960, 540"
validation_percentage = 0

[mlflow]
use_mlflow = false # Set to true when you want to save your model on MLFlow
tracking_uri = "http://127.0.0.1:5000"
experiment_name = "experiment-name"
model_name = "model-name"
run = "run-name"
user = "user"
password = "password"